### ISSUE TITLE
MySQL issue

### ISSUE THREAD

**Issue by l3st4tPlugins** [spyproof/NicknameManager#4]
**Description**
Basically, I have this plugin set up with MySQL, and it works fine, but after around 8 hours, it starts to not work, and MySQL queries start to throw exceptions.

**What do I mean by not working?**
The plugin itself works, but MySQL doesn't.

**Error Log**
`[18:29:07] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
[18:29:07] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:29:07] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:29:07] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:29:07] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.versionMeetsMinimum(ConnectionImpl.java:5206)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.prepareCall(ConnectionImpl.java:3967)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.prepareCall(ConnectionImpl.java:3948)
[18:29:07] [Server thread/WARN]:        at be.spyproof.nickmanager.da.player.MySqlPlayerStorage.getPlayerSql(MySqlPlayerStorage.java:337)
[18:29:07] [Server thread/WARN]:        at be.spyproof.nickmanager.da.player.MySqlPlayerStorage.getPlayer(MySqlPlayerStorage.java:139)
[18:29:07] [Server thread/WARN]:        at be.spyproof.nickmanager.controller.PlayerController.getStoredPlayer(PlayerController.java:108)
[18:29:07] [Server thread/WARN]:        at be.spyproof.nickmanager.controller.PlayerController.wrap(PlayerController.java:63)
[18:29:07] [Server thread/WARN]:        at be.spyproof.nickmanager.listeners.PlayerListener.onLogin(PlayerListener.java:34)
[18:29:07] [Server thread/WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor302.execute(Unknown Source)
[18:29:07] [Server thread/WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[18:29:07] [Server thread/WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[18:29:07] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:29:07] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
[18:29:07] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:565)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:152)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[18:29:07] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[18:29:07] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[18:29:07] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[18:29:07] [Server thread/WARN]:
[18:29:07] [Server thread/WARN]: The last packet successfully received from the server was 33,051,095 milliseconds ago.  The last packet sent successfully to the server was 10 milliseconds ago.
[18:29:07] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:29:07] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:29:07] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:29:07] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.DatabaseMetaData$8.forEach(DatabaseMetaData.java:4123)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.DatabaseMetaData$8.forEach(DatabaseMetaData.java:4087)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.DatabaseMetaData.getProceduresAndOrFunctions(DatabaseMetaData.java:4085)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.DatabaseMetaData.getProcedureOrFunctionColumns(DatabaseMetaData.java:3930)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.JDBC4DatabaseMetaData.getProcedureColumns(JDBC4DatabaseMetaData.java:108)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.CallableStatement.determineParameterTypes(CallableStatement.java:779)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.CallableStatement.<init>(CallableStatement.java:569)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.JDBC4CallableStatement.<init>(JDBC4CallableStatement.java:42)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.JDBC42CallableStatement.<init>(JDBC42CallableStatement.java:35)
[18:29:07] [Server thread/WARN]:        at sun.reflect.GeneratedConstructorAccessor262.newInstance(Unknown Source)
[18:29:07] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:29:07] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.CallableStatement.getInstance(CallableStatement.java:471)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.parseCallableStatement(ConnectionImpl.java:3905)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.prepareCall(ConnectionImpl.java:3972)
[18:29:07] [Server thread/WARN]:        ... 22 more
[18:29:07] [Server thread/WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
[18:29:07] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
[18:29:07] [Server thread/WARN]:        ... 46 more`

Is there any way to fix this?

**Comment by spyproof** [comment]
Could you try the latest version and provide feedback if this fixed it? 

https://github.com/spyproof/NicknameManager/releases/tag/1.1.1

**Comment by l3st4tPlugins** [comment]
I'll try it as soon as possible! Thank you!

**Comment by l3st4tPlugins** [comment]
Seems to work fine so far, however, I do have a small question. Can you add a BungeeCord side plugin so I can get the nickname in the proxy side?

**Comment by spyproof** [comment]
I am not familiar with bungee at all so if you want an interaction like that you can hire a developer and ask them to expand this plugin with it.

As a reminder, this plugin is 100% free and open source under the GNU licence, this means that you do NOT need to pay me any fees for using my code but any changes you do make and publish also need to be free of charge.
